# Main Hyprland config
# Sources all other configs

source = ./envs.conf
source = ./monitors.conf
source = ./input.conf
source = ./looknfeel.conf
source = ./bindings.conf
source = ./rules.conf
source = ./autostart.conf
source = ./decorations.conf
