[General]
type=greeter
version=1.0
theme=My Custom Theme

[Theme]
# The QML file to load
MainScript=Main.qml

# Custom variables for QML to read
Background="assets/background.gif"
BackgroundMode="fill"

